include: package:flutter_lints/flutter.yaml


linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    use_super_parameters: false
    use_build_context_synchronously: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    prefer_relative_imports: true