name: usage_log_flutter
description: "An Usage Log for Android built with Flutter."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  android_package_manager: ^0.7.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  usage_stats: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
